tree-sitter/node-tree-sitter

- .travis.yml
It seems that Travis is using Trusty by default now. A new-enough version of clang might already be installed.
> Use the default clang on travis

- index.js
- package.json
- src/binding.cc
- src/conversions.cc
- src/node.cc
- src/node.h
- src/parser.cc
- src/tree.cc
- src/tree.h
Depends on https://github.com/tree-sitter/tree-sitter/pull/181
In this PR, I've also added a method for finding the region of a syntax tree that has been directly edited: `Tree.getEditedRange`. This is also useful for https://github.com/atom/atom/pull/17551.
🍐'd with @queerviolet
> Add SyntaxNode.descendantsOfType method

- tree-sitter.d.ts
These changes:
* Fix several Typescript errors (given in the extended commit message for the fix)
* Updates the type organization to more closely match the exports of the module
* Updates a few of the types to match the current library API (eg `Edit` was wrong, `Document` was still being referred to, etc)
The correct way to do Typescript imports is now like this:
```typescript
import * as Parser from 'tree-sitter';
import { Point, SyntaxNode, Tree } from 'tree-sitter';
```
> Fix Typescript types

- index.js
- package.json
- src/node.cc
- src/node.h
- src/parser.cc
- src/tree.cc
- src/tree.h
In this PR, we've moved the syntax tree's cache of nodes from JS into C++. This allows us to use *weak* references in the cache, so that we'll only maintain pointers to nodes that are retained elsewhere. This way, when we edit the syntax tree, we'll know which syntax nodes we need to update.
🍐'd with @queerviolet 
Fixes https://github.com/tree-sitter/node-tree-sitter/issues/17
> Update the start positions of referenced nodes when editing a syntax tree

- .travis.yml
- appveyor.yml
- package.json
This adds support to prebuild binaries via [prebuild](https://github.com/prebuild/prebuild). This will prebuild binaries in Darwin, Linux, and Windows (32 and 64 bit) for all [supported targets in the node-api project](https://github.com/lgeiger/node-abi/blob/master/index.js#L51-L68). You can see how the binaries end up being built/uploaded on my test release version [v0.12.16.2](https://github.com/wingrunr21/node-tree-sitter/releases/tag/v0.12.16.2).
I'm hoping the Travis Linux OS is enough to provide support for Linux electron builds. If additional binaries are required the TravisCI config might have to be modified to build under additional Linux targets.
[prebuild-install](https://github.com/prebuild/prebuild-install) is used to download the prebuilt binaries via a custom `install` …
> Prebuild support

- index.js
- package.json
This adds a `.text` property to syntax nodes so that you can conveniently access their text without having to manually slice the source string using the node's `startIndex` and `endIndex`.
I was originally hesitant to add this because it was trivially achievable already and I wasn't sure if all applications would want to retain the source string in memory after parsing, but it seems like most users probably want this.
Closes https://github.com/tree-sitter/node-tree-sitter/issues/22
> Add text accessors for nodes and tree cursors

- index.js
- src/node.cc
- src/node.h
- src/tree_cursor.cc
- src/tree_cursor.h
- tree-sitter.d.ts
This PR adds support to the `TreeCursor` object for `ts_tree_cursor_current_node` and `ts_tree_cursor_reset` as discussed in #30 and #31.
A few notes on the implementation:
1. I had to make `UnmarshalNode` a non-static function so I could use it in `TreeCursor::Reset`. I think it could be kept `static` but we'd need to suppress the GCC warnings. I didn't see a reason making it non-static could be detrimental but I might be missing some context.
2. The way I got at the `Tree` instance in the cursor in order to marshal/unmarshal the nodes works but I feel like there's a better way to do it.
3. Both functions make the assumption that the tree exists as an attribute on the cursor. Given this assignment is done in the `walk` method of `SyntaxNode`, this is a bit of a bummer. I'm thinking a …
> Add reset and currentNode support to TreeCursor

- binding.gyp
- index.js
- src/parser.cc
This PR bumps Tree-sitter, bringing in this change: https://github.com/tree-sitter/tree-sitter/pull/301. I've updated the `Parser.parseTextBuffer` API to use the new timeout functionality.
Now, instead of this:
```js
const tree = await parser.parseTextBuffer(buffer, oldTree, {
syncOperationLimit: 1000 // 1000 abstract "parsing operations"
})
```
you do this:
```js
const tree = await parser.parseTextBuffer(buffer, oldTree, {
syncTimeoutMicros: 1500  // 1.5 milliseconds
})```
> Update to latest Tree-sitter

- .appveyor.yml
- .travis.yml
- binding.gyp
- index.js
- package.json
- src/binding.cc
- src/language.cc
- src/language.h
- src/node.cc
- src/parser.cc
- test/node_test.js
- test/parser_test.js
- test/tree_test.js
This PR exposes the new *node fields* APIs introduced in https://github.com/tree-sitter/tree-sitter/pull/271.
When using a language that includes fields (like these branches of [tree-sitter-javascript](https://github.com/tree-sitter/tree-sitter-javascript/pull/96), [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python/pull/39) and [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash/pull/43)), syntax tree nodes will have different subclasses. Each node will have getters for its different fields.
Example:
```js
const tree = parser.parse(`
class A {
@autobind
@something
b(c, d) {
return c + d;
}
}
`);
const classNode = tree.rootNode.firstChild;
const methodNode = classNode.bodyNode.firstNamedChild;
// Subclasses named after the node types …
```
> Auto-generate Node subclasses with getters for node fields

- .gitmodules
This PR changes the submodule for `tree-sitter` to point to the `atom` fork (more specifically https://github.com/atom/tree-sitter/tree/node-tree-sitter-submodule).
This branch contains a cherry-pick of https://github.com/tree-sitter/tree-sitter/pull/361 on top of https://github.com/tree-sitter/tree-sitter/commit/77636e8fe6418c10a1c2ddb7a278c886bff7ef35 (which is the commit that's currently used by the submodule on `node-tree-sitter`).
> Target submodule to avoid using clock_gettime on macOS

- .travis.yml
The Linux binaries that are created on Travis are causing problems for the Atom build. For the last two releases, I've had to delete the prebuilt Linux binaries in order to get the Atom Travis builds to pass.
I think the problem may be that these binaries are compiled with gcc. Atom [uses clang](https://github.com/atom/atom/blob/7aaf836c0da01fb55a48caf152d636e8d76dec3f/.travis.yml#L19), and [so does `node-keytar`](https://github.com/atom/node-keytar/blob/35b90d11acf9142e1c589668df9095fa0bde9236/.travis.yml#L10), Atom's other native dependency with `prebuild` support. Clang and gcc create binaries with dependencies on two different C++ standard library implementations.
For now, I'm going to switch the `node-tree-sitter` builds to also use clang on Linux. Hopefully this ends up working for …
> Use clang for linux travis builds

- package.json
This is to match tree-sitter/tree-sitter-ruby#108
Happy to drop support for < 4.0 like we did there as well.
Note I'm currently working on the WASM move but need a few PRs in tree-sitter proper to land first.
> Prebuild against 4.0.4 and 5.0.0

- tree-sitter.d.ts
A Range contains:
- `startIndex`
- `endIndex`
- `startPosition`
- `endPosition`
> Fix the TypeScript definition of a Range

- tree-sitter.d.ts
The function signature of `Parser.prototype.parse` defined in `index.js`
```JS
Parser.prototype.parse = function(input, oldTree, {bufferSize, includedRanges}={})
```
accepts a third optional parameter.
This commit reflects the signature in TypeScript definition.
depends on #64
> Add bufferSize and includedRanges options to parse function in TS def

- index.js
- package.json
- tree-sitter.d.ts
* Added missing ts tree-sitter.d.ts declarations
* Synced query parameter names with wasm binding
> Added missing ts tree-sitter.d.ts declarations

- package.json
- src/query.cc
Fixes #72
This PR resolves the issue due to automatic `Nan::Utf8String` destructor call due to outing of scope on line [108](https://github.com/tree-sitter/node-tree-sitter/compare/master...ahlinc:fix/segmentation-fault/72?expand=1#diff-5df376ef3534aee11e2e44e6e42e8e90da079dd96ac7da487a99bc6653366fdcL108) what leads to:
```
source == "\0"
source_len > 0
```
so `ts_query_new` function would try to read a lot of bytes from a string contained in the destructed `Nan::Utf8String` object whose memory is most likely to be freed already in case of a long input string.
> fix: prevent Nan::Utf8String destructor call due to out of scope

- binding.gyp
- src/conversions.cc
- src/node.cc
Changed the ArrayBuffer API to use new way so it compiles on Node 14+
> Use the new ArrayBuffer API for Electron 13

- index.js
- package.json
- test/query_test.js
Fixes: #107
This is just the same fix as https://github.com/tree-sitter/tree-sitter/commit/79b2bf1c30c65e8450f3712fcaffa39c6c3301b1
Also contains a drive-by fix to use https when cloning the tree-sitter-javascript repo as a dev dependency.
> Fix: Query fails to match optional node when using #eq? predicate

- package.json
- src/conversions.cc
- src/logger.cc
- src/node.cc
- src/parser.cc
- src/util.cc
- src/util.h
`GetCreationContext` was introduced in https://github.com/v8/v8/commit/b38bf5b0b1f149f7af3fd90a2ce12344e7191d03 released as V8 version 9.1 (probably, I'm just looking at the `git tag`s the commit belongs to and the state of https://github.com/v8/v8/blob/main/include/v8-version.h when the commit is made). Later they added a `GetCreationContextChecked` in https://github.com/v8/v8/commit/91475f958a044bf756314e43a4601b4f09abfe4b 9.7.64 which does the same thing as `CreationContext`. `CreationContext` was removed in commit [46224e7](https://github.com/v8/v8/commit/46224e75f3a42fb7ab1291c63d642e69dcdb4ac9#diff-33c4d36aeca8daf49e5dc90e3753462292180290ffd6b0d5a88ed55ab58a7817L5101) released as 10.3 (the commit says 10.2 but I think it's lying). So as per [this …
> Make code compilable on Node 19

- .github/workflows/build.yml
- binding.gyp
- package.json
Run
```sh
npx prebuild -t 10.0.0 -t 12.0.0 -t 14.0.0 -t 16.0.0 -t 18.0.0 -t 20.0.0 --strip
npx prebuild -r electron -t 3.0.0 -t 4.0.0 -t 5.0.0 -t 6.0.0 -t 7.0.0 -t 8.0.0 -t 9.0.0 -t 10.0.0 -t 11.0.0 -t 12.0.0 -t 13.0.0 -t 14.0.0 -t 15.0.0 -t 16.0.0 -t 17.0.0 -t 18.0.0 -t 19.0.0 -t 20.0.0 -t 21.0.0 -t 22.0.0 -t 23.0.0 -t 24.0.0 -t 25.0.0 --strip
```
in the CI under Node 16, 18 and 20 on Windows Server 2019, macOS 12 and Ubuntu 22.04. It won't work on Node 18+ before superstring is removed (#141), after that it won't work on Windows on Electron 13+, so the CI will start failing for all PRs but at least we can see the problem.
> Prebuild most Node and Electron versions in CI

- src/conversions.cc
- src/node.cc
- src/util.cc
and fix typo in macro from #134
> Partially revert #95

- src/conversions.cc
- src/node.cc
> Support Electron 13+ on Windows

- src/tree_cursor.cc
- src/tree_cursor.h
- test/tree_test.js
- tree-sitter.d.ts
During my research into tree-sitter CST traversal, I found out that Node.js tree-sitter binding doesn't contain cached getter `nodeIsMissing`. Because of that, when using TreeCursor, the only way to determine if the SyntaxNode is missing is to call the `cursor.currentNode.isMissing()` method. By doing this, traversal performance goes out the window. [web-binding](https://github.com/tree-sitter/tree-sitter/blob/de53b82e2c48d6221af9881e50cc57d961de3365/lib/binding_web/binding.c#L258) for tree-sitter exposes `nodeIsMissing` cached field, but Node.js binding doesn't. This PR remedies the situation.
**Before**:
```js
cursor = tree.walk();
cursor.currentNode.isMissing();
```
**After**:
```js
cursor = tree.walk();
cursor.nodeIsMissing;
```
Refs …
> feat: expose nodeIsMissing getter

- index.js
This prevents the VSCode debugger from crashing in the native bindings when trying to autocomplete properties on a `SyntaxNode` or when examining the prototype object.
> Insert sanity check in marshalNode

- package.json
npm has a "pre- and post- convention" for `scripts`
https://docs.npmjs.com/cli/v10/using-npm/scripts#pre--post-scripts
So this "`prebuild`" command is running every time you run `npm run build` (which happens if you have to compile the library yourself) and it's taking forever doing something useless.
> Remove prebuild commands from package.json

- .github/workflows/build.yml
Technically older Node.js versions require an even older machine to ensure compatibility, but many of those are EOL in practice...
Contributed on behalf of [Swimm](https://swimm.io/).
> Pin to Ubuntu 20.04 which is the actual minimum for at least Node 18

- .github/workflows/build.yml
- src/addon_data.h
- src/binding.cc
- src/conversions.cc
- src/conversions.h
- src/node.cc
- src/node.h
- src/parser.cc
- src/parser.h
- src/query.cc
- src/query.h
- src/tree.cc
- src/tree.h
- src/tree_cursor.cc
- src/tree_cursor.h
This makes this binding context aware, while still using v8/NaN/Node APIs directly, by moving all global data into an object, and removing global external buffers usage, which leads to seg faults/access violations on unloading the module.
The language bindings will also need to be made context aware which is done here https://github.com/tree-sitter/tree-sitter/pull/2841, and will need to be applied to each language binding.
Dropped supported for some ancient EOL Node.js and Electron versions so we don't have to ifdef for those.
Contributed on behalf of [Swimm](https://swimm.io/)
> Make the module context aware

- .github/workflows/build.yml
- binding.gyp
- index.js
- package.json
Replaces #101
```
npm notice package size:  1.1 MB                                  
npm notice unpacked size: 3.2 MB
```
> build: switch to prebuildify

- src/node.cc
- src/tree.cc
If this was the real cause for the Jest failures, we can possibly restore those tests as well.
This isn't the prettiest way to handle this code wise, so feel free to suggest something cleaner, and note that I also had to handle it in `CacheNodeForTree` which would assert when it tries to cache a node during this state.
@verhovsky @amaanq
> Fix for the NodeClass is not a constructor issue

- src/node.cc
LLVM >= 18 has deprecated and removed char_trait implementation for non char types in https://github.com/llvm/llvm-project/commit/c3668779c13596e223c26fbd49670d18cd638c40, for VSCode we build the native modules using libc++ and clang to align with the runtime, building current node-tree-sitter leads to the following error
```
/mnt/vss/_work/1/s/.build/libcxx_headers/include/__string/char_traits.h:617:23: error: implicit instantiation of undefined template 'std::char_traits<unsigned short>'
617 |   const _CharT* __r = _Traits::find(__p + __pos, __sz - __pos, __c);
|                       ^
/mnt/vss/_work/1/s/.build/libcxx_headers/include/string:3375:15: note: in instantiation of function template specialization 'std::__str_find<unsigned short, unsigned long, std::char_traits<unsigned …
```
> fix: compilation with clang >=18

- src/parser.cc
I noticed there was a large buildup of memory when repeatedly calling `parse` on a `Parser`. After digging into the issue it turns out that `input`, and therefore `inputString`, was being retained by `CallbackInput` 
https://github.com/tree-sitter/node-tree-sitter/blob/419da7d40a76046d53ae1c00aeafa2e0587a3e12/index.js#L355
This PR simply resets the resources in the destructor of `CallbackInput` to allow `input` and `inputString` to be garbage collected.
> Fix memory leak in CallbackInput

- .github/workflows/build.yml
This is the minimum supported by Node.js
Fixes #203
> Build prebuilds on Ubuntu 20.04

- tree-sitter.d.ts
> Remove `QueryCapture.text` from typings. It's not really there

- src/parser.cc
Caused by annoying limitation of Node-API where you can't create a reference to a String.
Fixes #199
> fix: Fix parsing when string is larger than buffer length

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- package.json
> ci: actually build arm64 binaries, & publish releases to gh
